Repository depromeet/SPOT-server, pull requests merged in 2024-07, with the labels that each got.

#4 [BSVR-54] Spotless pre-commit hook 추가
  .editorconfig
  .githooks/pre-commit
  .github/CODEOWNERS
  .github/workflows/pr-size-labeler.yaml
  application/src/main/java/org/depromeet/spot/application/SpotApplication.java
  application/src/main/java/org/depromeet/spot/application/config/SpotApplicationConfig.java
  application/src/main/java/org/depromeet/spot/application/sample/controller/SampleController.java
  application/src/main/java/org/depromeet/spot/application/sample/controller/request/SampleRequest.java
  application/src/main/java/org/depromeet/spot/application/sample/controller/response/SampleResponse.java
  build.gradle.kts
Labels: 🛠 Setting, size/XL

#5 [BSVR-52] Gradle refreshVersion 플러그인 적용
  application/build.gradle.kts
  build.gradle.kts
  settings.gradle.kts
  versions.properties
Labels: size/S, 🔨 Build

#9 [BSVR-61] 윈도우에서 makeGitHooksExecutable 에러 fix
  build.gradle.kts
Labels: 🐛 Bug, 🔨 Build, size/XS

#6 [BSVR-44] 영속성 계층 (JPA) 모듈 추가
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/config/SpotApplicationConfig.java
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/request/MemberRequest.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java
  application/src/main/resources/application.yaml
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  infrastructure/build.gradle.kts
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/.gitkeep
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/JpaConfig.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  settings.gradle.kts
  usecase/.gitignore
  usecase/build.gradle.kts
  usecase/src/main/java/org/depromeet/spot/usecase/config/UsecaseConfig.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java
  versions.properties
Labels: size/M

#10 [BSVR-62] 개발단계 ci github actions 스크립트 추가
  .github/workflows/dev-ci.yaml
Labels: 🚀 CI/CD, size/S

#12 [BSVR-55] P6spy를 이용한 쿼리 로그 설정
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/.gitkeep
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/P6spySqlFormatter.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/P6spyConfig.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  versions.properties
Labels: 🛠 Setting, size/S

#13 [BSVR-56] QueryDSL 설정 추가
  .editorconfig
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/QueryDslConfig.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberCustomRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java
  versions.properties
Labels: 🛠 Setting, 🔨 Build, size/M

#14 [BSVR-64] PR 템플릿 수정 & Issue 템플릿 추가
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/suggest.md
  .github/pull_request_template.md
Labels: 📝 Docs, size/S

#15 [BSVR-63] custom exception & global exception handler 추가
  .gitignore
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java
  application/src/main/java/org/depromeet/spot/application/common/exception/ErrorResponse.java
  application/src/main/java/org/depromeet/spot/application/common/exception/SpotAppExceptionHandler.java
  common/.gitignore
  common/build.gradle.kts
  common/src/main/java/org/depromeet/spot/common/exception/BusinessException.java
  common/src/main/java/org/depromeet/spot/common/exception/ErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java
  settings.gradle.kts
  usecase/build.gradle.kts
  usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java
Labels: ✨ Feature, size/M

#11 [BSVR-25] docker 추가
  .gitignore
  Dockerfile.dev
  docker-compose.yml
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/resources/application-jpa.yaml
Labels: size/M

#17 [BSVR-81] Domain과 Entity 기본 세팅
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java
  domain/src/main/java/org/depromeet/spot/domain/block/Block.java
  domain/src/main/java/org/depromeet/spot/domain/block/BlockRow.java
  domain/src/main/java/org/depromeet/spot/domain/block/BlockTopKeyword.java
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  domain/src/main/java/org/depromeet/spot/domain/review/Keyword.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  domain/src/main/java/org/depromeet/spot/domain/review/ReviewImage.java
  domain/src/main/java/org/depromeet/spot/domain/review/ReviewKeyword.java
  domain/src/main/java/org/depromeet/spot/domain/seat/Seat.java
  domain/src/main/java/org/depromeet/spot/domain/section/Section.java
  domain/src/main/java/org/depromeet/spot/domain/stadium/Stadium.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/main/java/org/depromeet/spot/domain/team/StadiumHomeTeam.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockRowEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockTopKeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/KeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewImageEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewKeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/entity/SeatEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/entity/StadiumEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/StadiumHomeTeamEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/MemberService.java
Labels: 🛠 Setting, size/XL

#18 [BSVR-92] 경기장 조회 API들
  application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/StadiumReadController.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumHomeTeamInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumInfoWithSeatChartResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumNameInfoResponse.java
  common/src/main/java/org/depromeet/spot/common/exception/stadium/StadiumErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/stadium/StadiumException.java
  common/src/main/java/org/depromeet/spot/common/exception/util/UtilErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/util/UtilException.java
  domain/build.gradle.kts
  domain/src/main/java/org/depromeet/spot/domain/common/RgbCode.java
  domain/src/main/java/org/depromeet/spot/domain/section/Section.java
  domain/src/main/java/org/depromeet/spot/domain/stadium/Stadium.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/main/java/org/depromeet/spot/domain/team/StadiumHomeTeam.java
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/config/QueryDslConfig.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/entity/StadiumEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/StadiumHomeTeamCustomRepository.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/StadiumHomeTeamReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/stadium/StadiumRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/team/BaseballTeamRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/StadiumHomeTeamReadService.java
Labels: ✨ Feature, size/L, 🚀 Self Approve

#20 [BSVR-123] DB 컨벤션에 맞춰 BaseEntity 생성
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockRowEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockTopKeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/entity/BaseEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/KeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewImageEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewKeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/entity/SeatEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/entity/StadiumEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/StadiumHomeTeamEntity.java
Labels: ♻️ Refactor, ✨ Feature, size/L

#21 [BSVR-97] 특정 경기장 구역 내 블럭 리스트 조회
  application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java
  application/src/main/java/org/depromeet/spot/application/block/dto/response/BlockCodeInfoResponse.java
  common/src/main/java/org/depromeet/spot/common/exception/section/SectionErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/section/SectionException.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumRepositoryImpl.java
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/section/SectionRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/stadium/StadiumRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeStadiumRepository.java
Labels: ✨ Feature, size/M

#24 [BSVR-103] 야구 팀(구단) 등록 & 조회 API
  application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeRequest.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java
  application/src/main/java/org/depromeet/spot/application/team/ReadBaseballTeamController.java
  application/src/main/java/org/depromeet/spot/application/team/dto/request/CreateBaseballTeamReq.java
  application/src/main/java/org/depromeet/spot/application/team/dto/response/BaseballTeamLogoRes.java
  common/src/main/java/org/depromeet/spot/common/exception/team/TeamErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/team/TeamException.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamJdbcRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/team/BaseballTeamRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBaseballTeamRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/section/SectionReadServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/stadium/StadiumReadServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamServiceTest.java
Labels: ✨ Feature, size/L

#26 [BSVR-27] 개발환경 CI/CD 세팅
  .github/workflows/dev-ci.yaml
  .github/workflows/dev-cicd.yaml
  .github/workflows/main-ci.yaml
  .gitignore
  docker-compose.yml
  infrastructure/jpa/src/main/resources/application-jpa.yaml
Labels: 🚀 CI/CD, size/M, 🚀 Self Approve

#27 [BSVR - 27] 개발환경 CI/CD ver.2
  .github/workflows/dev-cicd.yaml
Labels: 🚀 CI/CD, 🚀 Self Approve

#28 [BSVR-27] 개발환경 CICD v.3
  .github/workflows/dev-cicd.yaml
  Dockerfile
Labels: 🚀 CI/CD, 🚀 Self Approve

#29 [BSVR-27] 개발환경 CICD ver.3
  .github/workflows/dev-cicd.yaml
Labels: 🚀 CI/CD, 🚀 Self Approve

#16 [BSVR-68] 미디어 업로드를 위한 presigned url 생성 컴포넌트
  .gitignore
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java
  application/src/main/java/org/depromeet/spot/application/media/MediaController.java
  application/src/main/java/org/depromeet/spot/application/media/dto/request/CreatePresignedUrlRequest.java
  application/src/main/java/org/depromeet/spot/application/media/dto/response/MediaUrlResponse.java
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/resources/application.yaml
  build.gradle.kts
  common/src/main/java/org/depromeet/spot/common/exception/media/MediaErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/media/MediaException.java
  docker-compose.yml
  domain/src/main/java/org/depromeet/spot/domain/media/Media.java
  domain/src/main/java/org/depromeet/spot/domain/media/MediaProperty.java
  domain/src/main/java/org/depromeet/spot/domain/media/extension/ImageExtension.java
  domain/src/main/java/org/depromeet/spot/domain/media/extension/StadiumSeatMediaExtension.java
  domain/src/test/java/org/depromeet/spot/domain/media/MediaTest.java
  domain/src/test/java/org/depromeet/spot/domain/media/extension/ImageExtensionTest.java
  domain/src/test/java/org/depromeet/spot/domain/media/extension/StadiumSeatMediaExtensionTest.java
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  infrastructure/ncp/build.gradle.kts
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/NcpConfig.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/config/ObjectStorageConfig.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/FileNameGenerator.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGenerator.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ObjectStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ReviewStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/StadiumStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/resources/application.yaml
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/mock/FakeAmazonS3Config.java
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/mock/FakeTimeUsecase.java
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/FileNameGeneratorTest.java
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGeneratorTest.java
  infrastructure/ncp/src/test/resources/application-test.yml
  settings.gradle.kts
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/util/TimeUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/CreatePresignedUrlPort.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/util/TimeService.java
  versions.properties
Labels: size/XL

#30 [BSVR-27] 개발환경 CICD ver.4
  .github/workflows/dev-cicd.yaml
Labels: 🚀 CI/CD, 🚀 Self Approve

#31 [BSVR-27] 개발환경 CICD ver.5
  .github/workflows/dev-cicd.yaml
Labels: 🚀 CI/CD, size/XS, 🚀 Self Approve

#25 [BSVR-98] 블록별 열/번 조회 API
  application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java
  application/src/main/java/org/depromeet/spot/application/block/dto/response/BlockInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/block/dto/response/RowInfoResponse.java
  domain/src/main/java/org/depromeet/spot/domain/block/Block.java
  domain/src/main/java/org/depromeet/spot/domain/block/BlockRow.java
  domain/src/main/java/org/depromeet/spot/domain/seat/Seat.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/entity/BlockRowEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockCustomRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/entity/SeatEntity.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/block/BlockReadServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java
Labels: ✨ Feature, size/M

#33 [BSVR-91] 경기장 등록 API & 이미지 업로드 컴포넌트
  application/src/main/java/org/depromeet/spot/application/media/MediaController.java
  application/src/main/java/org/depromeet/spot/application/stadium/CreateStadiumController.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumResponse.java
  common/src/main/java/org/depromeet/spot/common/exception/media/MediaErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/media/MediaException.java
  domain/src/main/java/org/depromeet/spot/domain/media/MediaProperty.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/stadium/repository/StadiumRepositoryImpl.java
  infrastructure/ncp/build.gradle.kts
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/config/ObjectStorageConfig.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/ImageUploader.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGenerator.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ObjectStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/ReviewStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/property/StadiumStorageProperties.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/resources/application.yaml
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGeneratorTest.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/CreateStadiumUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/CreatePresignedUrlPort.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/ImageUploadPort.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/CreateStadiumService.java
Labels: ✨ Feature, size/M

#35 [BSVR-99] 경기장 내 구역 정보 생성
  application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeRequest.java
  application/src/main/java/org/depromeet/spot/application/section/CreateSectionController.java
  application/src/main/java/org/depromeet/spot/application/section/dto/request/CreateSectionRequest.java
  common/src/main/java/org/depromeet/spot/common/exception/section/SectionErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/section/SectionException.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionJdbcRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/CreateSectionUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/section/SectionRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/section/CreateSectionService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/section/CreateSectionServiceTest.java
Labels: ✨ Feature, size/M

#37 [BSVR-127] 멤버 Entity 변경
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  domain/src/main/java/org/depromeet/spot/domain/member/enums/MemberRole.java
  domain/src/main/java/org/depromeet/spot/domain/member/enums/SnsProvider.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
Labels: ♻️ Refactor, size/S, 🚀 Self Approve

#36 [BSVR]-119 내 시야기록 조회 API 구현
  application/src/main/java/org/depromeet/spot/application/review/ReviewReadController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/BlockReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/MyReviewRequest.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewCustomRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReviewReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReviewReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewReadServiceTest.java
Labels: ✨ Feature, size/M

#32 [BSVR-27] 개발환경 CI/CD 세팅
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/dev-ci.yaml
  .github/workflows/manual-prod-deploy.yaml
  Dockerfile
  docker-compose.yml
  infrastructure/jpa/src/main/resources/application-jpa.yaml
Labels: 🛠 Setting, 🚀 CI/CD, size/M

#38 [BSVR-104] 경기장별 홈 팀 등록 API
  application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java
  application/src/main/java/org/depromeet/spot/application/team/dto/request/CreateHomeTeamReq.java
  common/src/main/java/org/depromeet/spot/common/exception/team/TeamException.java
  domain/src/main/java/org/depromeet/spot/domain/team/StadiumHomeTeam.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/hometeam/HomeTeamJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/hometeam/HomeTeamRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/hometeam/StadiumHomeTeamCustomRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateHomeTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/team/BaseballTeamRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/team/HomeTeamRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateHomeTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBaseballTeamRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeHomeTeamRepository.java
Labels: size/XS, 🚀 Self Approve

#39 [BSVR-130] 경기장 조회 API res에 썸네일 추가
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumInfoWithSeatChartResponse.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
Labels: ✨ Feature, size/S, 🚀 Self Approve

#40 [BSVR-131] 전체 경기장 이름 조회 API에 isActive 필드 추가
  application/src/main/java/org/depromeet/spot/application/stadium/StadiumReadController.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumNameInfoResponse.java
  infrastructure/ncp/src/main/resources/application-ncp.yaml
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
Labels: ✨ Feature, size/XS, 🚀 Self Approve

#41 [BSVR-129] 블록의 열별 좌석 범위 조회 API
  application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java
  common/src/main/java/org/depromeet/spot/common/exception/block/BlockErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/block/BlockException.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRowJpaRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java
Labels: ✨ Feature, size/M

#42 [BSVR-127] 멤버 Entity 변경
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
Labels: ♻️ Refactor, size/XS, 🚀 Self Approve

#43 [NO_JIRA] 블록별 좌석 범위 조회 API request 수정
  application/src/main/java/org/depromeet/spot/application/block/BlockReadController.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRowJpaRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java
Labels: ✨ Feature, size/S

#44 [BSVR-100] 특정 경기장 내 블럭 & 블럭 내 열, 좌석 생성 API
  application/src/main/java/org/depromeet/spot/application/block/CreateBlockController.java
  application/src/main/java/org/depromeet/spot/application/block/dto/request/CreateBlockRequest.java
  common/src/main/java/org/depromeet/spot/common/exception/block/BlockErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/block/BlockException.java
  domain/src/main/java/org/depromeet/spot/domain/seat/Seat.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/row/BlockRowJdbcRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/row/BlockRowJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/row/BlockRowRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatJdbcRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatRepositoryImpl.java
  usecase/build.gradle.kts
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/BlockReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/CreateBlockUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/CreateRowUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/ReadBlockRowUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/seat/CreateSeatUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRowRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/CreateBlockService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/CreateRowService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/ReadBlockRowService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/seat/CreateSeatService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/block/CreateBlockServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBlockRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/seat/CreateSeatServiceTest.java
Labels: ✨ Feature, size/L

#34 [BSVR-71] 로그인/회원가입, JWT 구현
  .gitignore
  application/.gitignore
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtToken.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/request/RegisterReq.java
  application/src/main/resources/application.yaml
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java
  infrastructure/jpa/build.gradle.kts
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberCustomRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/oauth/OauthRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/oauth/entity/KakaoTokenEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/oauth/entity/KakaoUserInfoEntity.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/oauth/OauthRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  versions.properties
Labels: ✨ Feature, size/L, ❌ do not merge

#46 [BSVR-136] 프로필 이미지 presigned url API & 프로필 수정 API
  application/src/main/java/org/depromeet/spot/application/media/MediaController.java
  application/src/main/java/org/depromeet/spot/application/media/dto/request/CreatePresignedUrlRequest.java
  application/src/main/java/org/depromeet/spot/application/member/controller/UpdateMemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/request/UpdateProfileRequest.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberProfileResponse.java
  domain/src/main/java/org/depromeet/spot/domain/media/MediaProperty.java
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  infrastructure/jpa/src/main/resources/application-jpa.yaml
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/FileNameGenerator.java
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGenerator.java
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/FileNameGeneratorTest.java
  infrastructure/ncp/src/test/java/org/depromeet/spot/ncp/objectstorage/PresignedUrlGeneratorTest.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/ReadMemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/UpdateMemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/media/CreatePresignedUrlPort.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/ReadMemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/UpdateMemberService.java
Labels: ✨ Feature, size/M

#48 [BSVR-134] github release 관련한 github action 스크립트 파일 수정 및 배포 테스트
  .github/workflows/dev-build-and-deploy.yaml
  infrastructure/jpa/src/main/resources/application-jpa.yaml
Labels: 🚀 CI/CD, size/S, 🚀 Self Approve

#51 [NO_JIRA] 좌석배치도 미리보기 파일 확장자 변경
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/objectstorage/ImageUploader.java
Labels: ✨ Feature, size/XS

#52 [NO_JIRA] 업로드 가능한 최대 파일 사이즈 조정
  application/src/main/resources/application.yaml
Labels: 🛠 Setting, size/XS

#53 [BSVR-137] 복수 팀 등록 API를 단일 등록으로 수정
  application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java
  application/src/main/java/org/depromeet/spot/application/team/dto/request/CreateBaseballTeamReq.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeImageUploadPort.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamServiceTest.java
Labels: ✨ Feature, size/M

#54 [BSVR-138] ncp object storage 환경변수 추가
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🚀 CI/CD, size/XS, 🚀 Self Approve

#55 [NO_JIRA] 좌석 등록 중 불필요한 정렬 삭제
  usecase/src/main/java/org/depromeet/spot/usecase/service/seat/CreateSeatService.java
Labels: 🐛 Bug, size/XS

#56 [NO_JIRA] 전체 경기장 조회 API에 isActive, 이름 오름차순 정렬 추가
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/hometeam/StadiumHomeTeamCustomRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
Labels: size/S

#57 [NO_JIRA] JwtTokenResponse 추가
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/JwtTokenResponse.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberResponse.java
Labels: ♻️ Refactor, size/S, 🚀 Self Approve

#62 [NO_JIRA_KAKAO_oauth] 로그인 시 존재하지 않는 유저는 빈 JWT 리턴하도록 변경
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
Labels: ♻️ Refactor, size/XS, 🚀 Self Approve

#63 [BSVR-142] 구역 내 블록 조회시 블럭 코드 오름차순 정렬
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/block/repository/BlockJpaRepository.java
Labels: ✨ Feature, size/XS

#64 [NO_JIRA] accessToken을 사용한 멤버 삭제 API
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
Labels: ✨ Feature, size/S, 🚀 Self Approve

#66 [BSVR-78] Jwt 토큰 수정, 헤더 jwt 토큰에서 memberId 가져오는 AOP 추가
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/annotation/CurrentMember.java
  application/src/main/java/org/depromeet/spot/application/common/aop/JwtTokenAspect.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtToken.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenEnums.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/oauth/OauthRepositoryImpl.java
Labels: ♻️ Refactor, ✨ Feature, size/M

#68 [NO_JIRA] members 테이블 내의 사용하지 않는 컬럼 제거
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
Labels: size/XS, 📂 Database

#69 [BSVR-132] 블록별 리뷰조회 API, 유저별 리뷰조회 API, 유저별 리뷰 작성 날짜 조회 API 업데이트
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/KeywordResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  domain/src/main/java/org/depromeet/spot/domain/review/image/TopReviewImage.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/common/entity/BaseEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/dto/BlockTopKeywordDto.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/dto/TopReviewImageDto.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/ReviewEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/image/ReviewImageEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/entity/keyword/ReviewKeywordEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/image/ReviewImageJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/image/ReviewImageRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/keyword/BlockTopKeywordJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/keyword/BlockTopKeywordRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/keyword/KeywordRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/BlockTopKeywordRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/KeywordRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewImageRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: size/XL

#67 [BSVR-146] MemberInfo API 구현
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MyHomeResponse.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
Labels: ✨ Feature, size/S

#70 [BSVR-149] DB 스키마 복구를 위해 dev-build-and-deploy.yaml ddl-auto 옵션 update로 변경
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🚀 CI/CD, size/XS, 🚀 Self Approve

#72 [BSVR-150] blockId, seatNumber를 이용하도록 리뷰 생성 API 수정
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/seat/repository/SeatRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
Labels: ✨ Feature, size/S

#71 [BSVR-151] ddl-auto update 옵션으로 deploy
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🚀 CI/CD, size/XS, 🚀 Self Approve

#75 [CI/CD] dev-build-and-deploy.yaml ddl-auto 옵션 validate로 변경
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🚀 CI/CD, size/XS

#78 [BSVR-159] 리뷰 삭제 API 구현 (soft delete)
  application/src/main/java/org/depromeet/spot/application/review/DeleteReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/DeleteResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/DeleteReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/M

#80 [BSVR-161] 내 리뷰 조회 API response에 칭호 추가
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/XS

#83 [BSVR-162] 블록별 리뷰 조회 Location 정보 최상단으로 응답 구조 변경
  .gitignore
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/S

#82 [BSVR-152] 회원 탈퇴 soft delete API
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
Labels: ♻️ Refactor, ✨ Feature, size/S

#81 [BSVR-160] 홈 피드 화면 리뷰 도메인 API 추가
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MyHomeResponse.java
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyRecentReviewResponse.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ♻️ Refactor, ✨ Feature, size/M, 📂 Database

#84 [BSVR-162] 내 리뷰 조회 API 사용자 정보 리뷰와 독립적이도록 업데이트
  application/src/main/java/org/depromeet/spot/application/media/MediaController.java
  application/src/main/java/org/depromeet/spot/application/member/controller/UpdateMemberController.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/S

#85 [BSVR-163] 160 && 162 브랜치 Review Repository 쪽 충돌해결
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: 🐛 Bug, size/S

#90 [BSVR-169] 리뷰 생성 API req validation 업데이트: 키워드 개수 조건, 날짜 포맷
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateReviewRequest.java
  common/src/main/java/org/depromeet/spot/common/exception/review/ReviewErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/review/ReviewException.java
Labels: ✨ Feature

#91 [BUG] 프로필 prod->dev
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🐛 Bug, 🚀 CI/CD, size/XS
