Repository depromeet/SPOT-server, pull requests merged in 2024-08, with the labels that each got.

#92 [BSVR-174] 서버에서 관리하는 RGB를 Hexa Code로 변경
  application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeRequest.java
  application/src/main/java/org/depromeet/spot/application/common/dto/RgbCodeResponse.java
  application/src/main/java/org/depromeet/spot/application/section/dto/request/CreateSectionRequest.java
  application/src/main/java/org/depromeet/spot/application/section/dto/response/SectionInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java
  common/src/main/java/org/depromeet/spot/common/exception/util/UtilErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/util/UtilException.java
  domain/src/main/java/org/depromeet/spot/domain/common/HexCode.java
  domain/src/main/java/org/depromeet/spot/domain/common/RgbCode.java
  domain/src/main/java/org/depromeet/spot/domain/section/Section.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/test/java/org/depromeet/spot/domain/common/HexCodeTest.java
  domain/src/test/java/org/depromeet/spot/domain/common/RgbCodeTest.java
  domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/entity/SectionEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/section/repository/SectionJdbcRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/repository/BaseballTeamJdbcRepository.java
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/CreateSectionUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBaseballTeamRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/section/SectionReadServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamServiceTest.java
Labels: ✨ Feature, size/M, 📂 Database

#93 [BSVR-173] 리뷰 pk로 특정 리뷰 조회 API 구현
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/M

#94 [BSVR-168] 홈 팀 label 폰트 색상 추가
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
Labels: ✨ Feature, size/S, 📂 Database

#95 [BSVR-183] 레벨 계산 로직 변경
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
Labels: ✨ Feature, size/S, 🚀 Self Approve

#96 [BSVR-167] 레벨 도메인 분리 및 레벨별 칭호, 마스코트 이미지 추가
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MemberReviewProfileResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  domain/src/main/java/org/depromeet/spot/domain/member/Level.java
  domain/src/main/java/org/depromeet/spot/domain/member/Member.java
  domain/src/main/java/org/depromeet/spot/domain/member/enums/Level.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/LevelEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/LevelJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/LevelRepositoryImpl.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberJpaRepository.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/MemberRepositoryImpl.java
  infrastructure/jpa/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/ReadLevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/UpdateMemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/LevelRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/ReadLevelService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/UpdateMemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/L, 📂 Database

#97 [NO_JIRA] 리뷰 작성 API res에 레벨 업데이트 전 멤버 정보가 반환되는 버그
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
Labels: 🐛 Bug, size/S

#99 [BSVR-184] 내 리뷰 조회 API res 수정 : 팀이름, 팀 id 포함
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/S

#102 [NO_JIRA] Member 응원 팀을 nullable로 변경
  application/src/main/java/org/depromeet/spot/application/member/dto/request/RegisterReq.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/entity/MemberEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/UpdateMemberService.java
Labels: ✨ Feature, size/S, 📂 Database

#100 [BSVR-176] 홈 피드 화면 조회 API GUI 버전 적용
  application/src/main/java/org/depromeet/spot/application/member/controller/MemberController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/MyHomeResponse.java
  domain/src/main/java/org/depromeet/spot/domain/member/Level.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: size/S

#101 [BSVR-180] 레벨업 테이블 조회 API
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/member/controller/LevelUpTableController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/LevelUpTableResponse.java
  domain/build.gradle.kts
  domain/src/main/java/org/depromeet/spot/domain/member/Level.java
  infrastructure/jpa/src/main/java/org/depromeet/spot/jpa/member/repository/LevelRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/LevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/LevelRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java
Labels: size/M

#103 [BSVR-185] spring actuator, prometheus, loki 의존성 및 설정
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/resources/appenders/console-appender.xml
  application/src/main/resources/application.yaml
  application/src/main/resources/logback-spring.xml
  versions.properties
Labels: 🛠 Setting, size/M

#104 [NO_JIRA] immutable map fix
  domain/build.gradle.kts
  domain/src/main/java/org/depromeet/spot/domain/member/Level.java
Labels: ♻️ Refactor, size/S, 🔨 Build

#105 [BSVR-186] s3 연결 및 운영환경 수동배포 테스트
  .github/workflows/manual-prod-deploy.yaml
  infrastructure/ncp/src/main/java/org/depromeet/spot/ncp/config/ObjectStorageConfig.java
  infrastructure/ncp/src/main/resources/application-ncp.yaml
Labels: ✅ Test, 🚀 CI/CD, size/S, 🚀 Self Approve

#106 [NO_JIRA] 홈 피드 API teamId null 시 발생하는 오류 수정
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/MemberUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
Labels: 🐛 Bug, size/S

#108 [NO_JIRA] reviews teamId null 일 때 오류 fix
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: 🐛 Bug, ♻️ Refactor, size/S

#109 [NO-JIRA] baseball-teams 조회 API jwt filter 제외 추가
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
Labels: 🐛 Bug, size/XS, 🚀 Self Approve

#111 [BSVR-188] Level up 다이얼로그용 API
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/member/controller/ReadLevelController.java
  application/src/main/java/org/depromeet/spot/application/member/dto/response/LevelUpDialogInfo.java
  domain/src/main/java/org/depromeet/spot/domain/member/Level.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/entity/LevelEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/LevelJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/LevelRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/LevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java
Labels: ✨ Feature, size/S

#113 [NO_JIRA] 리뷰 삭제시 멤버 레벨 재조정
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: 🐛 Bug, size/S

#110 [BSVR-166] 로컬 캐시 적용
  application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java
  infrastructure/build.gradle.kts
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/cache/CacheType.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/cache/config/CacheConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/seat/repository/SeatJpaRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/BlockReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/level/LevelService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/seat/ReadSeatService.java
  versions.properties
Labels: ✨ Feature, 🛠 Setting, 🔨 Build, size/M

#115 [NO_JIRA] banner.txt 추가
  application/src/main/resources/banner.txt
Labels: 🛠 Setting, size/S

#117 [NO_JIRA] 경기장 이미지 필드 길이 조정
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/stadium/entity/StadiumEntity.java
Labels: size/XS, 📂 Database

#119 [NO_JIRA] loki 설정 전까지 prod에 Loki Appender 비활성화
  application/src/main/resources/logback-spring.xml
Labels: size/XS, 🚀 Self Approve

#122 [BSVR-190] 개발 서버 AWS 마이그레이션
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
  .gitignore
  Dockerfile
  application/src/main/resources/appenders/console-appender.xml
  application/src/main/resources/application.yaml
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/config/ObjectStorageConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/objectstorage/ImageUploader.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/objectstorage/PresignedUrlGenerator.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/property/ObjectStorageProperties.java
  infrastructure/src/main/resources/application-ncp.yaml
  infrastructure/src/test/java/org/depromeet/spot/infrastructure/aws/PresignedUrlGeneratorTest.java
Labels: 🚀 CI/CD, size/M, 🚀 Self Approve

#123 [BSVR-189] JWT 필터 로직 수정, Filter Exception handling, Oauth exception
  application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
  application/src/main/java/org/depromeet/spot/application/common/exception/CustomJwtException.java
  application/src/main/java/org/depromeet/spot/application/common/exception/ErrorResponse.java
  application/src/main/java/org/depromeet/spot/application/common/exception/ExceptionHandlerFilter.java
  application/src/main/java/org/depromeet/spot/application/common/exception/JwtErrorCode.java
  application/src/main/java/org/depromeet/spot/application/common/exception/SpotAppExceptionHandler.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  common/src/main/java/org/depromeet/spot/common/exception/oauth/OauthErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/oauth/OauthException.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/OauthRepositoryImpl.java
Labels: 🐛 Bug, ♻️ Refactor, ✨ Feature, size/M

#125 [BSVR-200] 사용하지 않는 샘플 코드 삭제
  application/src/main/java/org/depromeet/spot/application/sample/controller/SampleController.java
  application/src/main/java/org/depromeet/spot/application/sample/controller/request/SampleRequest.java
  application/src/main/java/org/depromeet/spot/application/sample/controller/response/SampleResponse.java
Labels: size/S

#116 [NO_JIRA] Loki 모니터링 인스턴스 ip 설정
  .gitignore
  application/.gitignore
  application/src/main/resources/appenders/console-appender.xml
  application/src/main/resources/application.yaml
  application/src/main/resources/logback-spring.xml
Labels: 🛠 Setting, size/S

#127 [NO-JIRA] jwt fix
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  application/src/main/java/org/depromeet/spot/application/member/controller/JwtCreateController.java
Labels: 🐛 Bug, ✨ Feature, size/S

#133 [BSVR-210] 개발 서버 로키 connection 에러 트러블 슈팅
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
Labels: 🐛 Bug, 🚀 CI/CD, 🚀 Self Approve

#134 [NO_JIRA] loki 오류 fix
  application/src/main/resources/appenders/console-appender.xml
  application/src/main/resources/logback-spring.xml
Labels: 🐛 Bug, ♻️ Refactor, size/S

#136 [NO_JIRA] local profile에서 loki 비활성화
  application/src/main/resources/logback-spring.xml
Labels: 🛠 Setting

#137 [BSVR-194] 리뷰 등록 어드민 API + 관련 작업들
  application/src/main/java/org/depromeet/spot/application/member/controller/ReadLevelController.java
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateAdminReviewRequest.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/cache/CacheType.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/seat/entity/SeatEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/section/repository/SectionRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/ReadBlockRowUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/LevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/ReadLevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/member/level/ReadLevelUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRowRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/section/SectionRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/ReadBlockRowService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/level/ReadLevelService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/ReadLevelService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/UpdateMemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewImageProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewKeywordProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java
Labels: ✨ Feature, size/M, 📂 Database

#140 [BSVR-214] 개발 서버 자동 태그 생성 기능 삭제
  .github/workflows/dev-build-and-deploy.yaml
Labels: 🚀 CI/CD, size/S

#141 [NO_JIRA] 어드민 리뷰 등록시 키워드, 이미지 등록 로직 순서 변경
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
Labels: 🐛 Bug, size/XS

#145 [BSVR-212] AWS ElastiCache Redis 세팅
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
  application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java
  infrastructure/build.gradle.kts
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/InfrastructureConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedisConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedisProperties.java
  versions.properties
Labels: 🛠 Setting, 🔨 Build, size/M

#144 [BSVR-214] 리뷰 조회 offset에서 cursor 방식으로 변경 + 이전리뷰(seat nullable) 반영
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/BlockReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/MyReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewImageRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewKeywordRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReadReviewServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewReadServiceTest.java
Labels: ✨ Feature, size/XL, 🚀 Self Approve

#124 [BSVR-199] section, baseballTeam의 label color 삭제
  application/src/main/java/org/depromeet/spot/application/section/dto/request/CreateSectionRequest.java
  application/src/main/java/org/depromeet/spot/application/section/dto/response/SectionInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/HomeTeamInfoResponse.java
  application/src/main/java/org/depromeet/spot/application/team/CreateBaseballTeamController.java
  domain/src/main/java/org/depromeet/spot/domain/section/Section.java
  domain/src/main/java/org/depromeet/spot/domain/team/BaseballTeam.java
  domain/src/test/java/org/depromeet/spot/domain/team/BaseballTeamTest.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/section/entity/SectionEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/section/repository/SectionJdbcRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/team/entity/BaseballTeamEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/team/repository/BaseballTeamJdbcRepository.java
  infrastructure/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/CreateSectionUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/CreateBaseballTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/team/ReadStadiumHomeTeamUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/team/ReadStadiumHomeTeamService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeBaseballTeamRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSectionRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/section/SectionReadServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/CreateBaseballTeamServiceTest.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/team/ReadBaseballTeamServiceTest.java
Labels: ✨ Feature, size/M, ❌ do not merge, 📂 Database

#148 [BSVR-220] HashTag, BlockTag 도메인/엔티티 추가
  domain/src/main/java/org/depromeet/spot/domain/block/BlockTag.java
  domain/src/main/java/org/depromeet/spot/domain/hashtag/HashTag.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/entity/BlockTagEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/common/entity/BaseEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/hashtag/entity/HashTagEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/hashtag/repository/HashTagJpaRepository.java
  infrastructure/src/test/java/org/depromeet/spot/infrastructure/jpa/hashtag/HashTagEntityTest.java
Labels: size/M, 📂 Database

#146 [BSVR-196] 리뷰 공감 기능
  application/src/main/java/org/depromeet/spot/application/review/like/ReviewLikeController.java
  common/src/main/java/org/depromeet/spot/common/exception/review/ReviewErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/review/ReviewException.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  domain/src/main/java/org/depromeet/spot/domain/review/like/ReviewLike.java
  domain/src/test/java/org/depromeet/spot/domain/review/ReviewTest.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/like/ReviewLikeEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeRepositoryImpl.java
  infrastructure/src/main/resources/data.sql
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/UpdateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/like/ReviewLikeUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewLikeRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/like/ReviewLikeService.java
Labels: ✨ Feature, size/M, 📂 Database

#152 [BSVR-221] 특정 경기장 상세 정보 조회 API에 구역 정보, 블록 해시태그 정보 추가
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumBlockTagResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumInfoWithSeatChartResponse.java
  application/src/main/java/org/depromeet/spot/application/stadium/dto/response/StadiumSectionInfoResponse.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/entity/BlockTagEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/tag/BlockTagRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/block/ReadBlockTagUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/section/SectionReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/stadium/StadiumReadUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockTagRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/block/ReadBlockTagService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/section/SectionReadService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/stadium/StadiumReadService.java
Labels: ✨ Feature, size/M, 🚀 Self Approve, 📂 Database

#151 [BSVR-225] 리뷰 등록 api 열과 번 모두 nullable 하게 수정
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/processor/MemberLevelProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/processor/MemberLevelProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessorImpl.java
Labels: ♻️ Refactor, ✨ Feature, size/M

#153 [NO_JIRA] 이미지 파일 이름 받아오는 코드 수정
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/image/ReviewImageEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewImageProcessor.java
Labels: 🐛 Bug, size/XS

#154 [BSVR-225] 리뷰 등록 키워드 매핑 버그 수정 + 좋아요 순 정렬 기능 추가
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: 🐛 Bug, ✨ Feature, size/S, 🚀 Self Approve

#155 [BSVR-227] 스크랩 토글 API 구현
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  domain/src/main/java/org/depromeet/spot/domain/review/scrap/ReviewScrap.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/scrap/ReviewScrapEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/scrap/ReviewScrapUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: ✨ Feature, size/M

#156 [BSVR-231] 스크랩 개수 저장 로직 추가
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/UpdateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: ✨ Feature, 🚀 Self Approve

#157 [BSVR-228] 스크랩한 리뷰 내려주는 api 구현
  application/src/main/java/org/depromeet/spot/application/review/dto/request/PageRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/scrap/MyScrapRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/scrap/MyScrapListResponse.java
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/page/PageCommand.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/scrap/ReviewScrapUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: ✨ Feature, size/L, 🚀 Self Approve

#158 [BSVR-229] 등록 플로우 시야 후기, 직관 후기 분리
  application/src/main/java/org/depromeet/spot/application/review/dto/request/CreateReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/CreateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
Labels: ✨ Feature, size/S

#159 [BSVR-230] 블록 리뷰 조회 시야 후기 조회 + top review image 정책 업데이트
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BlockReviewListResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/image/ReviewImageRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewImageRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/M, 🚀 Self Approve

#161 [BSVR-241] 블록 리뷰에 유저가 좋아요, 스크랩을 눌렀는 지 안 눌렀는지 확인 필드 추가
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/BaseReviewResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/Review.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/like/ReviewLikeRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewLikeRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewScrapRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeReviewScrapRepository.java
Labels: ✨ Feature, size/M, 🚀 Self Approve

#162 [BSVR-242] 스크랩 조회 get요청에 request body쓴 이슈 + scrapsCount 조회 안되는 이슈 픽스
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: 🐛 Bug, ✨ Feature, size/S

#163 [BSVR-234] 시야 아카이빙 시야 후기/직관 후기 분리
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/dto/request/MyReviewRequest.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MemberInfoOnMyReviewResponse.java
  application/src/main/java/org/depromeet/spot/application/review/dto/response/MyReviewListResponse.java
  domain/src/main/java/org/depromeet/spot/domain/review/ReviewCount.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewCustomRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
Labels: ✨ Feature, size/M, 🚀 Self Approve

#164 [BSVR-244] 스크랩 조회 페이지네이션 커서 버그 픽스
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/scrap/ReviewScrapCustomRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/PaginationProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/PaginationProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: 🐛 Bug, ♻️ Refactor, size/M

#160 [BSVR-239] 로컬/테스트에서 redis를 사용하기 위한 세팅
  application/src/main/resources/application.yaml
  infrastructure/build.gradle.kts
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/EmbeddedRedisConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedissonConfig.java
  versions.properties
Labels: 🛠 Setting, size/S, 🔨 Build

#167 [NO-JIRA] oauth 환경 변수 추가
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
Labels: 🛠 Setting, 🚀 CI/CD, size/S, 🚀 Self Approve

#166 [BSVR-217] 리뷰 공감에 분산락 추가
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SpotApplicationConfig.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtProperties.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtTokenUtil.java
  application/src/test/java/org/depromeet/spot/application/ReviewLikeServiceTest.java
  application/src/test/resources/application-test.yml
  application/src/test/resources/sql/delete-data-after-review-like.sql
  application/src/test/resources/sql/review-like-service-data.sql
  common/src/main/java/org/depromeet/spot/common/annotation/DistributedLock.java
  infrastructure/build.gradle.kts
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/config/ObjectStorageConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/DistributedLockAop.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/aop/TransactionAop.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/common/util/SpringELParser.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/OauthRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/config/OauthProperties.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/entity/ReviewEntity.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/like/ReviewLikeUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/like/ReviewLikeService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/common/ConcurrencyTest.java
  versions.properties
Labels: size/L

#172 [fix/NO_JIRA] local & test 환경에서 embedded redis를 이용해 redisson 쓰도록 수정
  .gitignore
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/EmbeddedRedisConfig.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/redis/RedissonConfig.java
Labels: 🐛 Bug, ♻️ Refactor, size/S

#174 [BSVR-250] 어드민 리뷰 생성에서 ReviewType 때문에 insert에서 버그 발생
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
Labels: 🐛 Bug, size/XS

#176 [NO_JIRA] 기본 프로필 이미지 변경
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/GoogleUserInfoEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/KakaoUserInfoEntity.java
Labels: ♻️ Refactor, size/S

#177 [NO_JIRA] login fix
  application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/member/controller/OauthController.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberErrorCode.java
  common/src/main/java/org/depromeet/spot/common/exception/member/MemberException.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/entity/MemberEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/member/repository/MemberRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/member/MemberRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/oauth/OauthService.java
Labels: 🐛 Bug, ♻️ Refactor, size/M

#179 [NO_JIRA] login fix
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/aws/property/ObjectStorageProperties.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/OauthRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/GoogleUserInfoEntity.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/oauth/entity/KakaoUserInfoEntity.java
  infrastructure/src/test/java/org/depromeet/spot/infrastructure/aws/PresignedUrlGeneratorTest.java
Labels: 🐛 Bug, size/S, 🚀 Self Approve

#181 [BSVR-252] 어드민 리뷰 등록 Multipart 오류
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
Labels: 🐛 Bug, size/XS, 🚀 Self Approve
