Repository depromeet/SPOT-server, pull requests merged in 2024-09, with the labels that each got.

#165 [BSVR-232] 믹스패널 이벤트 추가
  .gitignore
  application/build.gradle.kts
  application/src/main/java/org/depromeet/spot/application/common/config/SecurityConfig.java
  application/src/main/java/org/depromeet/spot/application/common/jwt/JwtAuthenticationFilter.java
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/resources/application.yaml
  domain/src/main/java/org/depromeet/spot/domain/mixpanel/MixpanelEvent.java
  infrastructure/build.gradle.kts
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/mixpanel/property/MixpanelProperties.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/mixpanel/repository/MixpanelRepositoryImpl.java
  usecase/build.gradle.kts
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/ReadReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/mixpanel/MixpanelRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/like/ReviewLikeService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
  versions.properties
Labels: ✨ Feature, size/M, ❌ do not merge

#185 [BSVR-257] 리뷰 수정 API 업데이트 - 요청 필드 추가, nullable 처리
  application/src/main/java/org/depromeet/spot/application/review/dto/request/UpdateReviewRequest.java
  application/src/main/resources/application.yaml
  domain/src/main/java/org/depromeet/spot/domain/review/ReviewLocationInfo.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/block/repository/row/BlockRowRepositoryImpl.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/seat/repository/SeatRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/UpdateReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/block/BlockRowRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/seat/SeatRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewCreationProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewDataProcessorImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReviewKeywordProcessor.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/fake/FakeSeatRepository.java
Labels: ♻️ Refactor, ✨ Feature, size/M, 🚀 Self Approve

#188 [BSVR-260] 리뷰 수정 isLiked, isScrapped 버그 해결
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/UpdateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessor.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/processor/ReadReviewProcessorImpl.java
Labels: 🐛 Bug, ✨ Feature, size/S, 🚀 Self Approve

#186 [BSVR-253] Mixpanel Event Listener 사용하도록 리팩토링
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/like/ReviewLikeController.java
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  domain/src/main/java/org/depromeet/spot/domain/mixpanel/MixpanelEvent.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/mixpanel/repository/MixpanelRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/like/ReviewLikeUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/mixpanel/MixpanelRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/event/MixpanelEvent.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/event/MixpanelEventListener.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/CreateReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/ReadReviewService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/like/ReviewLikeService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/scrap/ReviewScrapService.java
  usecase/src/test/java/org/depromeet/spot/usecase/service/review/ReviewScrapServiceTest.java
Labels: ♻️ Refactor, size/M

#189 [BSVR-261] 로키 로그에 Spring Profile 추가
  application/src/main/resources/appenders/console-appender.xml
Labels: ♻️ Refactor, 🛠 Setting, size/XS, 🚀 Self Approve

#187 [BSVR-256] 환경변수 관리를 위한 AWS Secret Manger 도입 - V2
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
  .gitignore
  application/.gitignore
  application/src/main/resources/application-jwt.yml
  application/src/main/resources/application-monitoring.yml
  application/src/main/resources/application-oauth.yml
  application/src/main/resources/application-sentry.yml
  application/src/main/resources/application.yaml
  build.gradle.kts
  infrastructure/src/main/resources/application-aws.yaml
  infrastructure/src/main/resources/application-jpa.yaml
  infrastructure/src/main/resources/application-mixpanel.yaml
  versions.properties
Labels: ✨ Feature, 🛠 Setting, 🚀 CI/CD, size/M

#191 [NO_JIRA] heic 이미지 확장자 추가
  domain/src/main/java/org/depromeet/spot/domain/media/extension/ImageExtension.java
Labels: ✨ Feature, size/XS, 🚀 Self Approve

#193 [BSVR-262] Secret Manger Loggin Appender 관련 버그 픽스
  .github/workflows/dev-build-and-deploy.yaml
  .github/workflows/manual-prod-deploy.yaml
Labels: 🐛 Bug, size/XS, 🚀 Self Approve

#194 [NO_JIRA] Loki profile fix
  application/src/main/resources/appenders/console-appender.xml
Labels: 🐛 Bug, size/XS, 🚀 Self Approve

#190 [BSVR-254] 탈퇴 시 리뷰 삭제 구현
  application/src/main/java/org/depromeet/spot/application/member/controller/JwtCreateController.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewJpaRepository.java
  infrastructure/src/main/java/org/depromeet/spot/infrastructure/jpa/review/repository/ReviewRepositoryImpl.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/in/review/DeleteReviewUsecase.java
  usecase/src/main/java/org/depromeet/spot/usecase/port/out/review/ReviewRepository.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/member/MemberService.java
  usecase/src/main/java/org/depromeet/spot/usecase/service/review/DeleteReviewService.java
Labels: ♻️ Refactor, size/S

#195 [NO-JIRA] 메모리 업
  Dockerfile
Labels: ♻️ Refactor, size/XS, 🚀 Self Approve

#196 [NO_JIRA] 메모리 업
  Dockerfile
Labels: ♻️ Refactor, size/XS, 🚀 Self Approve

#197 [NO_JIRA] 커넥션 풀 최대 300으로 설정
  infrastructure/src/main/resources/application-jpa.yaml
Labels: 🐛 Bug, size/XS, 🚀 Self Approve

#198 [NO-JIRA] mixpanel remove
  application/src/main/java/org/depromeet/spot/application/review/CreateReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/ReadReviewController.java
  application/src/main/java/org/depromeet/spot/application/review/like/ReviewLikeController.java
  application/src/main/java/org/depromeet/spot/application/review/scrap/ReviewScrapController.java
  infrastructure/src/main/resources/application-jpa.yaml
Labels: 🐛 Bug, size/S, 🚀 Self Approve
